### ISSUE TITLE
build with kernel 3.10.0

### ISSUE THREAD

**Issue by maxmo74** [veithen/knetstat#8]
Hi,

with kernel 3.10.0-514.10.2.el7 in RHEL7/Centos7/OEL7 we get:

make -C /lib/modules/3.10.0-514.10.2.el7.x86_64/build M=/home/user/knetstat modules
make[1]: Entering directory `/usr/src/kernels/3.10.0-514.10.2.el7.x86_64'
  CC [M]  /home/user/knetstat/knetstat.o
/home/user/knetstat/knetstat.c: In function ‘tcp_seq_show’:
/home/user/knetstat/knetstat.c:160:3: error: implicit declaration of function ‘seq_setwidth’ [-Werror=implicit-function-declaration]
   seq_setwidth(seq, 23);
   ^
/home/user/knetstat/knetstat.c:163:3: error: implicit declaration of function ‘seq_pad’ [-Werror=implicit-function-declaration]
   seq_pad(seq, ' ');
   ^
cc1: some warnings being treated as errors
make[2]: *** [/home/user/knetstat/knetstat.o] Error 1
make[1]: *** [_module_/home/user/knetstat] Error 2
make[1]: Leaving directory `/usr/src/kernels/3.10.0-514.10.2.el7.x86_64'
make: *** [all] Error 2

**Comment by veithen** [comment]
The current master branch is not compatible with kernels before 3.13. You need to build an older knetstat version. I've created a branch called "linux-pre-3.13" that points to the last version compatible with older kernels.

**Comment by maxmo74** [comment]
Thanks a lot!

Unfortunately with this branch it's now producing other errors:

$ make clean
make -C /lib/modules/3.10.0-514.10.2.el7.x86_64/build M=/home/user/knetstat clean
make[1]: Entering directory `/usr/src/kernels/3.10.0-514.10.2.el7.x86_64'
  CLEAN   /home/user/knetstat/.tmp_versions
make[1]: Leaving directory `/usr/src/kernels/3.10.0-514.10.2.el7.x86_64'

$ make
make -C /lib/modules/3.10.0-514.10.2.el7.x86_64/build M=/home/user/knetstat modules
make[1]: Entering directory `/usr/src/kernels/3.10.0-514.10.2.el7.x86_64'
  CC [M]  /home/user/knetstat/knetstat.o
/home/user/knetstat/knetstat.c: In function ‘tcp_seq_show’:
/home/user/knetstat/knetstat.c:84:16: error: ‘const struct ipv6_pinfo’ has no member named ‘daddr’
      dest = &np->daddr;
                ^
/home/user/knetstat/knetstat.c:85:15: error: ‘const struct ipv6_pinfo’ has no member named ‘rcv_saddr’
      src = &np->rcv_saddr;
               ^
/home/user/knetstat/knetstat.c:103:19: error: implicit declaration of function ‘inet6_rsk’ [-Werror=implicit-function-declaration]
      const struct inet6_request_sock *ireq6 = inet6_rsk(v);
                   ^
/home/user/knetstat/knetstat.c:103:47: warning: initialization makes pointer from integer without a cast [enabled by default]
      const struct inet6_request_sock *ireq6 = inet6_rsk(v);
                                               ^
/home/user/knetstat/knetstat.c:104:18: error: dereferencing pointer to incomplete type
      src = &ireq6->loc_addr;
                  ^
/home/user/knetstat/knetstat.c:105:19: error: dereferencing pointer to incomplete type
      dest = &ireq6->rmt_addr;
                   ^
/home/user/knetstat/knetstat.c:107:17: error: ‘const struct inet_request_sock’ has no member named ‘loc_addr’
      src = &ireq->loc_addr;
                 ^
/home/user/knetstat/knetstat.c:108:18: error: ‘const struct inet_request_sock’ has no member named ‘rmt_addr’
      dest = &ireq->rmt_addr;
                  ^
In file included from include/linux/swab.h:4:0,
                 from include/uapi/linux/byteorder/little_endian.h:12,
                 from include/linux/byteorder/little_endian.h:4,
                 from ./arch/x86/include/uapi/asm/byteorder.h:4,
                 from include/asm-generic/bitops/le.h:5,
                 from ./arch/x86/include/asm/bitops.h:514,
                 from include/linux/bitops.h:36,
                 from include/linux/kernel.h:10,
                 from /home/user/knetstat/knetstat.c:20:
/home/user/knetstat/knetstat.c:111:23: error: ‘const struct inet_request_sock’ has no member named ‘rmt_port’
     destp = ntohs(ireq->rmt_port);
                       ^
include/uapi/linux/swab.h:106:32: note: in definition of macro ‘__swab16’
  (__builtin_constant_p((__u16)(x)) ? \
                                ^
include/linux/byteorder/generic.h:136:21: note: in expansion of macro ‘__be16_to_cpu’
 #define ___ntohs(x) __be16_to_cpu(x)
                     ^
include/linux/byteorder/generic.h:141:18: note: in expansion of macro ‘___ntohs’
 #define ntohs(x) ___ntohs(x)
                  ^
/home/user/knetstat/knetstat.c:111:13: note: in expansion of macro ‘ntohs’
     destp = ntohs(ireq->rmt_port);
             ^
/home/user/knetstat/knetstat.c:111:23: error: ‘const struct inet_request_sock’ has no member named ‘rmt_port’
     destp = ntohs(ireq->rmt_port);
                       ^
include/uapi/linux/swab.h:13:12: note: in definition of macro ‘___constant_swab16’
  (((__u16)(x) & (__u16)0x00ffU) << 8) |   \
            ^
include/uapi/linux/byteorder/little_endian.h:41:26: note: in expansion of macro ‘__swab16’
 #define __be16_to_cpu(x) __swab16((__force __u16)(__be16)(x))
                          ^
include/linux/byteorder/generic.h:136:21: note: in expansion of macro ‘__be16_to_cpu’
 #define ___ntohs(x) __be16_to_cpu(x)
                     ^
include/linux/byteorder/generic.h:141:18: note: in expansion of macro ‘___ntohs’
 #define ntohs(x) ___ntohs(x)
                  ^
/home/user/knetstat/knetstat.c:111:13: note: in expansion of macro ‘ntohs’
     destp = ntohs(ireq->rmt_port);
             ^
/home/user/knetstat/knetstat.c:111:23: error: ‘const struct inet_request_sock’ has no member named ‘rmt_port’
     destp = ntohs(ireq->rmt_port);
                       ^
include/uapi/linux/swab.h:14:12: note: in definition of macro ‘___constant_swab16’
  (((__u16)(x) & (__u16)0xff00U) >> 8)))
            ^
include/uapi/linux/byteorder/little_endian.h:41:26: note: in expansion of macro ‘__swab16’
 #define __be16_to_cpu(x) __swab16((__force __u16)(__be16)(x))
                          ^
include/linux/byteorder/generic.h:136:21: note: in expansion of macro ‘__be16_to_cpu’
 #define ___ntohs(x) __be16_to_cpu(x)
                     ^
include/linux/byteorder/generic.h:141:18: note: in expansion of macro ‘___ntohs’
 #define ntohs(x) ___ntohs(x)
                  ^
/home/user/knetstat/knetstat.c:111:13: note: in expansion of macro ‘ntohs’
     destp = ntohs(ireq->rmt_port);
             ^
/home/user/knetstat/knetstat.c:111:23: error: ‘const struct inet_request_sock’ has no member named ‘rmt_port’
     destp = ntohs(ireq->rmt_port);
                       ^
include/uapi/linux/swab.h:108:12: note: in definition of macro ‘__swab16’
  __fswab16(x))
            ^
include/linux/byteorder/generic.h:136:21: note: in expansion of macro ‘__be16_to_cpu’
 #define ___ntohs(x) __be16_to_cpu(x)
                     ^
include/linux/byteorder/generic.h:141:18: note: in expansion of macro ‘___ntohs’
 #define ntohs(x) ___ntohs(x)
                  ^
/home/user/knetstat/knetstat.c:111:13: note: in expansion of macro ‘ntohs’
     destp = ntohs(ireq->rmt_port);
             ^
/home/user/knetstat/knetstat.c:117:9: error: ‘TCP_SEQ_STATE_TIME_WAIT’ undeclared (first use in this function)
    case TCP_SEQ_STATE_TIME_WAIT: {
         ^
/home/user/knetstat/knetstat.c:117:9: note: each undeclared identifier is reported only once for each function it appears in
/home/user/knetstat/knetstat.c:124:19: error: implicit declaration of function ‘inet6_twsk’ [-Werror=implicit-function-declaration]
      const struct inet6_timewait_sock *tw6 = inet6_twsk((struct sock *)tw);
                   ^
/home/user/knetstat/knetstat.c:124:46: warning: initialization makes pointer from integer without a cast [enabled by default]
      const struct inet6_timewait_sock *tw6 = inet6_twsk((struct sock *)tw);
                                              ^
/home/user/knetstat/knetstat.c:125:17: error: dereferencing pointer to incomplete type
      dest = &tw6->tw_v6_daddr;
                 ^
/home/user/knetstat/knetstat.c:126:17: error: dereferencing pointer to incomplete type
      src  = &tw6->tw_v6_rcv_saddr;
                 ^
cc1: some warnings being treated as errors
make[2]: *** [/home/user/knetstat/knetstat.o] Error 1
make[1]: *** [_module_/home/user/knetstat] Error 2
make[1]: Leaving directory `/usr/src/kernels/3.10.0-514.10.2.el7.x86_64'
make: *** [all] Error 2

**Comment by veithen** [comment]
Could it be that IPv6 support is not enabled in the kernel config?

**Comment by maxmo74** [comment]
It is. It's the default RHEL7 (or Centos7 or OracleLinux7) kernel and config.

**Comment by veithen** [comment]
It has been a long time since I last used CentOS/Red Hat. If you send me the instructions to install the kernel sources etc., I can try to reproduce this on a cloud instance.

**Comment by fangzhen** [comment]
It seems that we could apply part of patch 6d2f6c9 (Line 68 - 131) on branch linux-pre-3.13 to make it work with kernel 3.10. The patch 6d2f6c9 uses seq_setwidth() and seq_pad() which is not included in 3.10.

**Comment by chengweiv5** [comment]
> It has been a long time since I last used CentOS/Red Hat. If you send me the instructions to install the kernel sources etc., I can try to reproduce this on a cloud instance.

I'm facing the same problem, and install kernel header on RHEL/CentOS is very simple, just run `yum install -y kernel-devel`.

Thanks!

**Comment by chengweiv5** [comment]
I enabled ipv6 and linux-pre-3.13 still build with failures

```
/root/knetstat/knetstat.c: In function ‘tcp_seq_show’:
/root/knetstat/knetstat.c:84:16: error: ‘const struct ipv6_pinfo’ has no member named ‘daddr’
      dest = &np->daddr;
                ^
/root/knetstat/knetstat.c:85:15: error: ‘const struct ipv6_pinfo’ has no member named ‘rcv_saddr’
      src = &np->rcv_saddr;
               ^
/root/knetstat/knetstat.c:103:19: error: implicit declaration of function ‘inet6_rsk’ [-Werror=implicit-function-declaration]
      const struct inet6_request_sock *ireq6 = inet6_rsk(v);
                   ^
/root/knetstat/knetstat.c:103:47: warning: initialization makes pointer from integer without a cast [enabled by default]
      const struct inet6_request_sock *ireq6 = inet6_rsk(v);
                                               ^
/root/knetstat/knetstat.c:104:18: error: dereferencing pointer to incomplete type
      src = &ireq6->loc_addr;
                  ^
/root/knetstat/knetstat.c:105:19: error: dereferencing pointer to incomplete type
      dest = &ireq6->rmt_addr;
                   ^
/root/knetstat/knetstat.c:107:17: error: ‘const struct inet_request_sock’ has no member named ‘loc_addr’
      src = &ireq->loc_addr;
                 ^
/root/knetstat/knetstat.c:108:18: error: ‘const struct inet_request_sock’ has no member named ‘rmt_addr’
      dest = &ireq->rmt_addr;
                  ^
In file included from include/linux/swab.h:4:0,
                 from include/uapi/linux/byteorder/little_endian.h:12,
                 from include/linux/byteorder/little_endian.h:4,
                 from ./arch/x86/include/uapi/asm/byteorder.h:4,
                 from include/asm-generic/bitops/le.h:5,
                 from ./arch/x86/include/asm/bitops.h:514,
                 from include/linux/bitops.h:36,
                 from include/linux/kernel.h:10,
                 from /root/knetstat/knetstat.c:20:
/root/knetstat/knetstat.c:111:23: error: ‘const struct inet_request_sock’ has no member named ‘rmt_port’
     destp = ntohs(ireq->rmt_port);
                       ^
include/uapi/linux/swab.h:106:32: note: in definition of macro ‘__swab16’
  (__builtin_constant_p((__u16)(x)) ? \
                                ^
include/linux/byteorder/generic.h:136:21: note: in expansion of macro ‘__be16_to_cpu’
 #define ___ntohs(x) __be16_to_cpu(x)
                     ^
include/linux/byteorder/generic.h:141:18: note: in expansion of macro ‘___ntohs’
 #define ntohs(x) ___ntohs(x)
                  ^
/root/knetstat/knetstat.c:111:13: note: in expansion of macro ‘ntohs’
     destp = ntohs(ireq->rmt_port);
             ^
/root/knetstat/knetstat.c:111:23: error: ‘const struct inet_request_sock’ has no member named ‘rmt_port’
...
...
```
