### PR TITLE
Add partial patch of 6d2f6c9

### LINKED ISSUE #8: build with kernel 3.10.0
Hi,

with kernel 3.10.0-514.10.2.el7 in RHEL7/Centos7/OEL7 we get:

make -C /lib/modules/3.10.0-514.10.2.el7.x86_64/build M=/home/user/knetstat modules
make[1]: Entering directory `/usr/src/kernels/3.10.0-514.10.2.el7.x86_64'
  CC [M]  /home/user/knetstat/knetstat.o
/home/user/knetstat/knetstat.c: In function ‘tcp_seq_show’:
/home/user/knetstat/knetstat.c:160:3: error: implicit declaration of function ‘seq_setwidth’ [-Werror=implicit-function-declaration]
   seq_setwidth(seq, 23);
   ^
/home/user/knetstat/knetstat.c:163:3: error: implicit declaration of function ‘seq_pad’ [-Werror=implicit-function-declaration]
   seq_pad(seq, ' ');
   ^
cc1: some warnings being treated as errors
make[2]: *** [/home/user/knetstat/knetstat.o] Error 1
make[1]: *** [_module_/home/user/knetstat] Error 2
make[1]: Leaving directory `/usr/src/kernels/3.10.0-514.10.2.el7.x86_64'
make: *** [all] Error 2

### PR DESCRIPTION
**Pull request by ogreface**
Per suggestion from @fangzhen, added a partial patch from 6d2f6c9.

This makes the build work, and should fix #8 

Tested on Centos7 3.10.0-862.3.2.el7.x86_64 #1 SMP

### CODE REVIEW

**Comment by veithen** [comment]
Thank you for your patch. I have decided to only maintain code for kernel versions that are not end of life. Please feel free to maintain code for earlier versions in your fork.
